
version: '3.8'

services:
  # Frontend React application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - app-network

  # Database - Add this if you need a direct connection to the database
  # This is optional as Supabase manages the database remotely
  # db:
  #   image: postgres:15-alpine
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: example
  #     POSTGRES_USER: example
  #     POSTGRES_DB: example
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

# Uncomment if using local database
# volumes:
#   postgres-data:
