// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxhhpwdhhlyplzkkrrpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4aGhwd2RoaGx5cGx6a2tycnB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2ODI0ODIsImV4cCI6MjA2MDI1ODQ4Mn0.kfaqswPpCcSkMQ7m7FuJB__chGzlpOD6g_-hPMgoE5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);